version: "3"

services:
  locations-recommender-api:
    image: node:12
    ports:
      - "3000:3000"
      - "9230:9229"
    volumes:
      - yarn:/root/.cache/yarn
      - .:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: ./entrypoint.sh
    command: yarn start:debug
    depends_on:
      - locations-recommender-db

  locations-recommender-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=locations_recommender
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

volumes:
  yarn:
